#!/usr/bin/env php
<?php

declare(strict_types=1);

$baseDir = __DIR__;

require $baseDir . '/vendor/autoload.php';

/** @var list<string> $cliArgv */
$cliArgv = $_SERVER['argv'] ?? [];

exit(App\Commands\BuildCommand::runFromArgv($cliArgv));
