#!/usr/bin/env php
<?php

declare(strict_types=1);

$baseDir = __DIR__;

require $baseDir . '/vendor/autoload.php';

if (is_file($baseDir . '/.env')) {
    (new Symfony\Component\Dotenv\Dotenv())->load($baseDir . '/.env');
}

/** @var list<string> $cliArgv */
$cliArgv = $_SERVER['argv'] ?? [];

exit(App\Commands\BuildCommand::runFromArgv($cliArgv));
