#!/usr/bin/env php
<?php

declare(strict_types=1);

$baseDir = __DIR__;

require $baseDir . '/vendor/autoload.php';

if (is_file($baseDir . '/.env')) {
    (new Symfony\Component\Dotenv\Dotenv())->load($baseDir . '/.env');
}

$application = new Symfony\Component\Console\Application('picoHP', '1.0.0');
$application->addCommand(new App\Commands\BuildCommand());

exit($application->run());
