; generated by picoHP
; ModuleID = test_module
target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
target triple = "arm64-apple-macosx14.0.0"

@.str.d = private constant [4 x i8] c"%d\0A\00", align 1
@.str.f = private constant [4 x i8] c"%f\0A\00", align 1

declare i32 @printf(ptr, ...)
define dso_local i32 @main() {
entry:
    %add_result5 = add i32 1, 2
    %icmpeq_result6 = icmp eq i32 %add_result5, 3
    br i1 %icmpeq_result6, label %if.then, label %if.else
if.then:
    br label %if.end
if.else:
    br label %if.end
if.end:
    ret i32 1
}
