<?php

namespace App\LLVM;

class BaseEmitter
{
    public function restart() {
         file_put_contents('out.ll', '; generated by php_compiler' . PHP_EOL);       
    }

    public function write(string $text) {
        file_put_contents('out.ll', $text, FILE_APPEND);
    }

    public function writeln(int $indent = 0, string $line = '') {
        file_put_contents('out.ll', str_repeat(' ', $indent * 4) . $line . PHP_EOL, FILE_APPEND);
    }
}