<?php

declare(strict_types=1);

namespace App\LLVM;

class BaseEmitter
{
    public function restart(): void
    {
        file_put_contents('out.ll', '; generated by php_compiler' . PHP_EOL);
    }

    public function write(string $text): void
    {
        file_put_contents('out.ll', $text, FILE_APPEND);
    }

    public function writeln(int $indent = 0, string $line = ''): void
    {
        file_put_contents('out.ll', str_repeat(' ', $indent * 4) . $line . PHP_EOL, FILE_APPEND);
    }

    public function begin(): void
    {
    }

    public function end(): void
    {
    }
}
