#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Writes phpstan.paths.generated.neon from the same reachable file set as
 * {@see \App\PicoHP\Precompile\CompilationPlanner} / directory {@code build}.
 *
 * Environment:
 *   PICOHP_PHPSTAN_ENTRY — path to entry file relative to project root (default: picohp)
 *   PICOHP_PHPSTAN_INCLUDE_TESTS — if "0", omit tests/ (strict compile-closure only). Default: include tests/ for CI parity with the old phpstan.neon layout.
 */

use App\PicoHP\Precompile\CompilationPlanner;

$projectRoot = dirname(__DIR__);
require $projectRoot . '/vendor/autoload.php';

$entryRel = getenv('PICOHP_PHPSTAN_ENTRY') ?: 'picohp';
$entryAbsolute = realpath($projectRoot . '/' . $entryRel);
if ($entryAbsolute === false || !is_file($entryAbsolute)) {
    fwrite(STDERR, "generate-phpstan-paths: entry file not found: {$entryRel}\n");

    exit(1);
}

$planner = new CompilationPlanner();
$plan = $planner->planDirectoryBuild($projectRoot, $entryAbsolute);

/** @var list<string> */
$paths = [];
foreach ($plan->reachableFiles as $file) {
    $r = realpath($file);
    if ($r !== false) {
        $paths[] = $r;
    }
}

$bootstrap = $projectRoot . '/bootstrap/functions.php';
if (is_file($bootstrap)) {
    $br = realpath($bootstrap);
    if ($br !== false && !in_array($br, $paths, true)) {
        $paths[] = $br;
    }
}

if (getenv('PICOHP_PHPSTAN_INCLUDE_TESTS') !== '0') {
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($projectRoot . '/tests', FilesystemIterator::SKIP_DOTS),
    );
    foreach ($iterator as $fileInfo) {
        if (!$fileInfo->isFile() || $fileInfo->getExtension() !== 'php') {
            continue;
        }
        $p = $fileInfo->getPathname();
        $rp = realpath($p);
        if ($rp !== false) {
            $paths[] = $rp;
        }
    }
}

$paths = array_values(array_unique($paths));
sort($paths);

$rootReal = realpath($projectRoot);
if ($rootReal === false) {
    fwrite(STDERR, "generate-phpstan-paths: could not resolve project root\n");

    exit(1);
}

$lines = [
    '# Generated by scripts/generate-phpstan-paths.php — do not edit by hand.',
    '# Regenerate: composer run-script phpstan-generate-paths',
    '',
    'parameters:',
    '    paths:',
];

foreach ($paths as $abs) {
    $rel = project_relative_path($rootReal, $abs);
    $lines[] = '        - ' . $rel;
}

$out = $projectRoot . '/phpstan.paths.generated.neon';
file_put_contents($out, implode("\n", $lines) . "\n");

fwrite(STDERR, 'Wrote ' . $out . ' (' . count($paths) . " paths)\n");

/**
 * @param non-falsy-string $rootReal
 */
function project_relative_path(string $rootReal, string $absolute): string
{
    $root = str_replace('\\', '/', $rootReal);
    $abs = str_replace('\\', '/', $absolute);
    $prefix = rtrim($root, '/') . '/';
    if (str_starts_with($abs, $prefix)) {
        return substr($abs, strlen($prefix));
    }

    return $absolute;
}
