#!/bin/sh

# TODO: convert to composer script

php -d memory_limit=-1 vendor/bin/phpstan analyse --configuration phpstan.neon --debug src               
composer install --no-dev --optimize-autoloader
composer dump-autoload --classmap-authoritative
../../picoHP build --debug .
