name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.4'
    - uses: actions/checkout@v4
    - name: Verify PHP Install
      run: php -i
    - name: Install LLVM
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm clang libffi-dev
    - name: Verify LLVM Version
      run: |
        which llvm-config
        llvm-config --version
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Run PHPStan
      run: composer run-script phpstan
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: vendor/bin/pest --coverage
    - name: Run Laravel Pint
      run: vendor/bin/pint --test
