name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-24.04

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: pre-installed
        ini-file: development
        ini-values: zend.assertions=1, assert.exception=1
        coverage: pcov
    - uses: actions/checkout@v4
    - name: Verify PHP Install
      run: php -i
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Run PHPStan
      run: composer run-script phpstan
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: vendor/bin/pest --coverage --min=95
    - name: Run Laravel Pint
      run: vendor/bin/pint --test
